version: "3.1"

services:
  scheduler:
    image: ghcr.io/dask/dask:latest
    hostname: scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    volumes:
      - /nvme/outbreak/bjornout:/nvme/outbreak/bjornout
    command: ["dask-scheduler"]

  worker:
    image: ghcr.io/dask/dask:latest
    command: ["dask-worker", "tcp://scheduler:8786"]
    volumes:
      - /nvme/outbreak/bjornout:/nvme/outbreak/bjornout
