#!/usr/bin/env bash

source init.sh

date '+%Y-%m-%d' > /data/start.txt
TMPDIR=$BJORN_TEMPDIR
./get_provision.sh "$BJORN_PROVDIR" "$BJORN_DAYSBACK" | ./readseqs.sh "$BJORN_PROVISION_DECODER" "$BJORN_PROVISION_PARSER" "$BJORN_ZINFO_DIR" "$BJORN_TEMPDIR" "$BJORN_READER_WORKGROUPS" "$BJORN_READER_WORKERSPER" > "$BJORN_TEMPDIR/bjorn_temp.tsv" && \
./analysis.sh "$BJORN_TEMPDIR/bjorn_temp.tsv" "$BJORN_ANALYSIS_WORKGROUPS" "$BJORN_ANALYSIS_WORKERSPER" "$BJORN_ANALYSIS_BLOCKSIZE" "$BJORN_TREEINFO_DIR" "$BJORN_TEMPDIR/anatemp" > "$BJORN_TEMPDIR/bjorn_temp_2.tsv" && cp "$BJORN_DATADIR/new.$BJORN_PERSISTFILE" "$BJORN_DATADIR/old.$BJORN_PERSISTFILE"
sort -m "$BJORN_TEMPDIR/bjorn_temp_2.tsv" "$BJORN_DATADIR/old.$BJORN_PERSISTFILE" | ./deduplicate.py | pv --line-mode > "$BJORN_DATADIR/new.$BJORN_PERSISTFILE" && cp "$BJORN_DATADIR/new.$BJORN_PERSISTFILE" "$BJORN_DATADIR/`date '+%Y-%m-%d'`.$BJORN_PERSISTFILE"
